### PR TITLE
corrected the code `at` and changed to `pt` 

### PR DESCRIPTION
**Pull request by Shayan-B**
correcte a typing blip in code for pytensor.tensor import

### CODE REVIEW

**Comment by twiecki** [comment]
Actually it should be `import pytensor.tensor as pt` everywhere. I think in another file it was also using `tt` maybe.

**Comment by Shayan-B** [comment]
> Actually it should be `import pytensor.tensor as pt` everywhere. I think in another file it was also using `tt` maybe.

You are right actually, I just gave this recommendation in order to make it compatible with the code after it,
so if we change it to `pt` we have to change the `T.stack` in the following code too.

**Comment by twiecki** [comment]
> so if we change it to pt we have to change the T.stack in the following code too.

Yes, you're right. Can you make these changes?

**Comment by Shayan-B** [comment]
> 

np

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Same in chapter 2: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/554/files#diff-9fc4a0e7834209ea34b4d28c88fadf5af42096ab64f5b4b0e4832b1aef201c0eR432
and 5: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/554/files#diff-c3fc32a9c505ecf8a7b24bead1eb807d7b267b5cf3675a302a916457892d9b8fR1090, 6: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/554/files#diff-199fdfea5b6b81e04e46186b1c01db27f75d876ddaad83a7e2c6c92f012394e2R1171

**Comment by twiecki** [comment]
Great, did you rerun the NBs to make sure it's all working?

**Comment by Shayan-B** [comment]
> Great, did you rerun the NBs to make sure it's all working?

I wasn't at my computer to test it, just replaced by search
but I can check them later to see if everything is working ok.
I will comment it here if everything run OK.

**Comment by Shayan-B** [comment]
> Great, did you rerun the NBs to make sure it's all working?

There was no error related to pytensor.
there were some errors and warnings with some other parts which needs to be fixed later.

**Comment by CamDavidsonPilon** [comment]
Sounds like it's good to merge?

**Comment by twiecki** [comment]
Yes!

@Shayan-B Can you open an issue about the errors that are present so we
don't lose track?

**Comment by Shayan-B** [comment]
@twiecki np, I'll do it.

**Pull request merged**
