### PR TITLE
Our PyMC3 port is complete!

### PR DESCRIPTION
**Pull request by mmargenot**
Please feel free to contact either Thomas or myself with any concerns you might have about our changes!

### CODE REVIEW

**Comment by mmargenot** [comment]
There were some changes made to PyMC3 related to positional arguments so I went through and corrected the examples that would have been affected.

**Comment by CamDavidsonPilon** [comment]
Thanks for the general cleanup of some of my old code too! 👌 
Overall, changes look good. I'm going to pull it locally and play around with PyMC3 too

**Comment by CamDavidsonPilon** [comment]
1. In the added header, you have my name as Cam Pilon, can you update it to Cam Davidson-Pilon?
2. In place of commented-out code, I think we should just delete it entirely. No value in keep it around.
3. The matplotlib styles are not the the same, but I can go through later and fix this (it happens often when another contributor wants to add content, but has rerun the plotting code).

**Comment by mmargenot** [comment]
Is there anywhere in particular that has commented-out code in an obtrusive place? I'm going through the individual scripts as they seem to have some.

What is the style that you are using? I can make a note to use it every time I re-run plots.

**Comment by CamDavidsonPilon** [comment]
It's the `.py` scripts mostly. A couple ways to update the style: 
1. (brute force) replacing the matplotlibrc file on your comp with https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/styles/matplotlibrc
2. using the code: `ply.styles.use('bmh')` before plotting anything (and I guess deleting the cell)
3. Ignore it 💃

**Comment by mmargenot** [comment]
I think I may ignore it for now.
:dancer: :dancer: :dancer:

**Comment by mmargenot** [comment]
Plot style should be good for each chapter now.

**Comment by CamDavidsonPilon** [comment]
👍 happy with this. Merging!

**Pull request merged**
