### PR TITLE
A merge for Bayesian Rugby

### PR DESCRIPTION
**Pull request by springcoil**
A little Bayesian Rugby example

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
Oh my! I'll give this a looks over tonight. Thanks @springcoil!

**Comment by springcoil** [comment]
Any views, or do I need to change some things. No immediate rush but I'd just like to unlock the achievement as soon as possible.

**Comment by syzer** [comment]
+1

**Comment by springcoil** [comment]
@CamDavidsonPilon Is this a first whole example contributed to this project?

**Comment by CamDavidsonPilon** [comment]
I didn't get a chance to look at it last night, unfortunately. I've opened it now - is it possible to do this without pandas? It's currently not a prerequisite, and I haven't introduced any pandas yet in the book. And yes, this is the first full example!

**Comment by springcoil** [comment]
Hi Cam,
Given the nature of the tabular data I think Pandas is the easiest way to
use it. It isn't actually needed for the PyMC based model.

On Wed, Mar 11, 2015 at 2:25 PM, Cameron Davidson-Pilon <
notifications@github.com> wrote:

> I didn't get a chance to look at it last night, unfortunately. I've opened
> it now - is it possible to do this without pandas? It's currently not a
> prerequisite, and I haven't introduced any pandas yet in the book. And yes,
> this is the first full example!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/249#issuecomment-78261626>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
I would recommend introducing pandas though. I have other examples in mind and it is a core part of the PyData stack.

**Comment by CamDavidsonPilon** [comment]
Hmm, I'm not 100% sold on Pandas - but it's okay for now. Can you add a note about Pandas? Something like, "Below we use the Pandas library to manipulate the data...". And also can you remove seaborn - or the graphs 100% reliant on it?

**Comment by springcoil** [comment]
Hi Cam,
I will when I head home.
Do I need to rebase to make these changes?

On Wed, Mar 11, 2015 at 5:54 PM, Cameron Davidson-Pilon <
notifications@github.com> wrote:

> Hmm, I'm not 100% sold on Pandas - but it's okay for now. Can you add a
> note about Pandas? Something like, "Below we use the Pandas library to
> manipulate the data...". And also can you remove seaborn - or the graphs
> 100% reliant on it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/249#issuecomment-78305096>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
Seaborn isn't necessary that was just for a bit of prettiness - but your
graphs are pretty enough

On Wed, Mar 11, 2015 at 5:58 PM, Peadar Coyle <peadarcoyle@googlemail.com>
wrote:

> Hi Cam,
> I will when I head home.
> Do I need to rebase to make these changes?
>
> On Wed, Mar 11, 2015 at 5:54 PM, Cameron Davidson-Pilon <
> notifications@github.com> wrote:
>
>> Hmm, I'm not 100% sold on Pandas - but it's okay for now. Can you add a
>> note about Pandas? Something like, "Below we use the Pandas library to
>> manipulate the data...". And also can you remove seaborn - or the graphs
>> 100% reliant on it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/249#issuecomment-78305096>
>> .
>>
>
>
>
> --
> Peadar Coyle
> Skype: springcoilarch
> www.twitter.com/springcoil
> peadarcoyle.wordpress.com
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by CamDavidsonPilon** [comment]
I don't think you will need to rebase, just push to your branch `BayesianRugby` and it will appear here.

**Comment by springcoil** [comment]
Hi
No problem :)

On Wed, Mar 11, 2015 at 6:11 PM, Cameron Davidson-Pilon <
notifications@github.com> wrote:

> I don't think you will need to rebase, just push to your branch
> BayesianRugby and it will appear here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/249#issuecomment-78308660>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
Ok I did what I was told :)

**Comment by CamDavidsonPilon** [comment]
Looks good to me! I might make some minor edits here and there to clean up the language, I hope you don't mind. Anyways, mergin!

**Comment by springcoil** [comment]
No problem. I don't object to minor edits you are the editor!

On Wednesday, March 11, 2015, Cameron Davidson-Pilon <
notifications@github.com> wrote:

> Merged #249
> <https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/249>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/249#event-250489728>
> .
>


-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Pull request merged**
