### PR TITLE
Updated Dependencies with note on TFP being in Colab's default runtime

### PR DESCRIPTION
**Pull request by matthew-mcateer**
So, three major changes
1) Deleted the tensorflow probability installation cell (since TFP is in the default runtime for colab, this was replaced with instructions on how to install TFP if you're running it locally
2) extra markdown added to the cell with the global variables in order to explain what those variables actually do
3) Re-ran chapters 2 and 4 with better resolution for the outputs

### CODE REVIEW

**Comment by matthew-mcateer** [comment]
@CamDavidsonPilon, There's a conflict?

**Comment by CamDavidsonPilon** [comment]
related to the fix here: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/420/files

Are you comfortable resolving?

**Comment by matthew-mcateer** [comment]
@Cameron  I resolved the conflict and also made a few updates to the formats of the equations. It should be all ready now.

**Comment by CamDavidsonPilon** [comment]
lgtm!

**Pull request merged**
