### PR TITLE
Added Tensorflow Probability Example

### PR DESCRIPTION
**Pull request by matthew-mcateer**
This new added Jupyter Notebook does away with mentions of PyMC2, PyMC3, and Theano, and
uses Google's Tensorflow probability for solving the same problems with the same concepts. There have also been increases to the resolutions of the matplotlib plots to show more detail on retina screens.

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
Some notes:
1. I'll add something to the README as soon as this is merged. 
2. TIL and ❤️ `InlineBackend.figure_format = 'retina'`
3. Locally, I commented out `assert tf.test.is_gpu_available()` - things _seem_ to work, but do we need to require this for users? I'd prefer the easier-to-install-and-learn option here. 

(more to be added)

**Comment by CamDavidsonPilon** [comment]
` Example: Cheating among students` has some `print` errors - however even after fixing them, I still can't get the example to run due to an `eval()` error. 

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-4e14523833b7> in <module>()
      2     observed_proportion_val = observed_proportion_calc(t_a=true_answers,
      3                                                        fc=first_coin_flips,
----> 4                                                        sc=second_coin_flips)
      5     print(observed_proportion_val)

<ipython-input-50-f15116f73129> in observed_proportion_calc(t_a, fc, sc)
     13     """
     14     observed = fc * t_a + (1 - fc) * sc
---> 15     observed_proportion = np.sum(observed.eval()) / float(N)
     16 
     17     return observed_proportion

AttributeError: 'numpy.ndarray' object has no attribute 'eval'
```

**Comment by matthew-mcateer** [comment]
@CamDavidsonPilon Glad to see those preliminary requests were to your liking.

**Comment by matthew-mcateer** [comment]
With a lot of the notebooks, it turned out that I had accidentally sent pull requests for the wrong version (which is apparently something that can happen when you're working with both local jupyter and online Google Colab).

**Comment by matthew-mcateer** [comment]
With two of the notebooks, I added the pull requests prematurely, because within these notebooks I include links to Github at the top of the notebook, and using the github link as a placeholder (i.e., linking directly to the notebook in the PR), was the most effective way we had at making sure a user could conceivably view any version of the notebook they wanted, whether that was a local copy, a copy in Github, or a copy in Colab.

**Comment by matthew-mcateer** [comment]
So with that in mind, we've seen a lot of the errors in the current pull request. We're going to be uploading much more stable versions in the near future (i.e., by week's end). We'll alert you when we've done so, @CamDavidsonPilon .

**Comment by matthew-mcateer** [comment]
Also, @CamDavidsonPilon, in these notebooks, in additon to the replacement o PyMC & SciPy with TFP, we're also working on replacing a majority of the Numpy code with Tensorflow and TFP as well. We just figured we'd update everyone on the scope change.

**Comment by matthew-mcateer** [comment]
Hey @CamDavidsonPilon , Here's a new version of the PR. We decided that it would probably be easier on you if just one chapter was committed at a time. With that in mind, here is a revised chapter 1 (which now includes some of the best practices for TFP semantics, AND also runs in both Graph and Eager mode for Tensorflow). A lot of the plotting has been updated as well.

**Comment by CamDavidsonPilon** [comment]
Hey @matthew-mcateer, looks great! Runs fine for me. Code looks good too. 

Merging the first chapter - excited to see the others next!

**Pull request merged**
