### PR TITLE
Use theano.tensor.switch instead of pm.switch

### PR DESCRIPTION
**Pull request by sebp**
pm.switch does not exist and is replaced by theano.tensor.switch (same as pm.math.switch) in PyMC3.

Chapter 1 already uses theano's switch.

### CODE REVIEW

**Comment by twiecki** [comment]
Actually these just moved to `pymc3.math`, can you import `switch` from there instead?

**Comment by sebp** [comment]
@twiecki  `pymc3.math.switch´ is used in chapters 1 and 2 now.

**Comment by twiecki** [comment]
Cool, LGTM. CC @CamDavidsonPilon

**Comment by CamDavidsonPilon** [comment]
👍 thanks for the contribution!

**Pull request merged**
