### PR TITLE
Fixed log-loss latex formula in Chapter 5

### PR DESCRIPTION
**Pull request by chdamianos**
I think the log-loss definition in Chapter 5 is wrong. 
The logarithm should be applied to the estimated probabilities.
I swapped around the `\\hat{}` to correct.

### CODE REVIEW

**Comment by CamDavidsonPilon** [comment]
A larger problem is that I have a subtraction sign between the terms, not an addition sign.

**Comment by chdamianos** [comment]
I think that's correct. You have minus on both terms.
https://en.wikipedia.org/wiki/Loss_functions_for_classification#Cross_entropy_loss_(Log_Loss)

**Comment by CamDavidsonPilon** [comment]
oh right okay

**Comment by CamDavidsonPilon** [comment]
w.r.t to these changes 👍

**Pull request merged**
